apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx_svc
  name: nginx_svc
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx_svc
  type: NodePort
status:
  loadBalancer: {}
